### ISSUE TITLE
[Bug]: No emails are forwarded because btree and hash for postfix aliases are unsupported

### ISSUE THREAD

**Issue by infinityofspace** [infinityofspace/simplelogin-docker-aio#8]
### OS info

Arch 6.6.8

### Docker version

24.0.7

### docker-compose version (optional)

2.23.3

### simplelogin-docker-aio version

v4.36.7-1

### Bug description

No emails are forwarded from any sender to any receiver email address.

### Relevant log output

```shell
postfix/smtpd[136]: warning: unsupported dictionary type: hash. Is the postfix-hash package installed?
error: unsupported dictionary type: hash                                                                                                       
postfix/tlsmgr[138]: warning: unsupported dictionary type: btree. Is the postfix-btree package installed?
postfix/tlsmgr[138]: error: unsupported dictionary type: btree
postfix/tlsmgr[138]: warning: unsupported dictionary type: btree. Is the postfix-btree package installed?
postfix/tlsmgr[138]: error: unsupported dictionary type: btree
postfix/tlsmgr[138]: warning: btree:/var/lib/postfix/smtpd_scache is unavailable. unsupported dictionary type: btree
postfix/tlsmgr[138]: warning: btree:/var/lib/postfix/smtp_scache is unavailable. unsupported dictionary type: btree
```

### Steps to reproduce

1. Start the container with the docker compose file:

```yml
version: "3.9"

services:
  simplelogin:
    image: ghcr.io/infinityofspace/simplelogin-docker-aio:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "25:25"
    volumes:
      - "data:/sl"
      - "uploads:/code/static/upload"
      - "letsencrypt:/etc/letsencrypt:ro"
      - "./simplelogin.env:/code/.env"
      - "./dkim:/dkim/"
    env_file:
      - db.env
      - simplelogin.env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  db:
    image: postgres:12.1
    restart: unless-stopped
    volumes:
      - "db_data:/var/lib/postgresql/data"
    env_file:
      - db.env

volumes:
  data:
  uploads:
  db_data:
  letsencrypt:
    name: letsencrypt
    external: true
```

```commandline
docker compose up -d
```

2. Email one of the simplelogin aliases.
3. Bug: no Email is forwarded and the error messages of the provides logs appear.

### Additional context

The error occurs with arbitrary simplelogin aliases and sender addresses.

### Checklist

- [X] I have checked for [existing Github issues](https://github.com/infinityofspace/simplelogin-docker-aio/issues) for the same bug.
- [X] I have checked to see if there is no current version that already fixes this error.
- [X] I have checked that I meet the [general and system requirements](https://github.com/infinityofspace/simplelogin-docker-aio/blob/main/Readme.md) for the use of this project.
